version: '3'

services:
  transaction-api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      AWS_MYSQL_URL: ${AWS_MYSQL_URL}
      AWS_MYSQL_USER: ${AWS_MYSQL_USER}
      AWS_MYSQL_PASS: ${AWS_MYSQL_PASS}